# nginx:1.17 이미지 컨테이너 한개 생성 후  80/TCP 포트 바인드하는 파드.
# 파드 생성 : kubectl apply -f sample-pod.yaml
# 파드 상세정보 표시 : kubectl get pods --output wide 


apiVersion: v1 
kind: Pod 
metadata:
  name: sample-pod 
spec:
  containers:
    - name: nginx-container 
      image: nginx:1.17