# 같은 containerPort를 사용하는 nginx 컨테이너를 여러개 생성하면 하나만 가동되고 나머지는 충돌이 나며 실행되지 않는다.
# 파드는 네트워크 네임스페이스를 공유하고 있으므로 일반 VM상에 80/TCP 포트를 바인드하는 서비스를 하나 이상 사용할 수 없는 환경과 같다고 보면 된다. 
# 파드 생성 : kubectl apply -f sample-2pod-fail.yaml
# 파드 조회 : kubectl get pods
# 파드 로그 확인 : kubectl logs sample-2pod-fail.yaml -c nginx-container-113 (컨테이너 지정 가능)


apiVersion: v1
kind: Pod 
metadata:
  name: sample-2pod
spec:
  containers:
    - name: nginx-container-112
      image: nginx:1.17
    - name: nginx-container-113
      image: nginx:1.16